apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: '75.6.1'
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path # Rancher Desktop default
                  accessModes: ['ReadWriteOnce']
                  resources:
                    requests:
                      storage: 10Gi

        grafana:
          enabled: true
          adminPassword: admin123 # Change this in production
          persistence:
            enabled: true
            storageClassName: local-path
            size: 5Gi
          service:
            type: NodePort
            nodePort: 30080

        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ['ReadWriteOnce']
                  resources:
                    requests:
                      storage: 2Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
