apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml
  - ingress.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
